name = "EnergyModels"
uuid = "411f25fd-c8c8-5884-8d62-1a208e38aa34"
keywords = ["optimization", "energy-model"]
license = "MIT"
desc = "Toolbox for optimizing modern power systems"
version = "0.0.2"

[deps]
AxisArrays = "39de3d68-74b9-583c-8d2d-e117c070f3a9"
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Destruct = "dde75ccc-4946-507f-85f2-ccadd28c929c"
JuMP = "4076af6c-e467-56ae-b986-b466b2749572"
LightGraphs = "093fc24a-ae57-5d10-9952-331d41423f4d"
Logging = "56ddb016-857b-54e1-b83d-db4d58db5568"
MathOptInterface = "b8f27783-ece8-5eb3-8dc8-9495eed66fee"
MetaGraphs = "626554b9-1ddb-594c-aa3c-2596fe9399a5"
NCDatasets = "85f8d34a-cbdd-5861-8df4-14fed0d494ab"
PowerModels = "c36e90e8-916a-50a6-bd94-075b64ef4655"
Requires = "ae029012-a4dd-5104-9daa-d747884805df"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"

[compat]
DataFrames = "~0.19"
julia = "^1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
